ALTER TABLE PRICING
ADD FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCT(PRODUCT_ID)

INSERT INTO product (PRODUCT_ID, PRODUCT_NAME, CREATED_DATE, MODIFIED_DATE, IS_ACTIVE) VALUES(101, 'Dalda', CURRENT_DATE(),CURRENT_DATE(),TRUE)